version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: social-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: social
    ports:
      - "5432:5432"
    volumes:
      # Persists data on the host machine
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:8.2.3-alpine
    restart: unless-stopped
    container_name: social-redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: social-redis-commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis

volumes:
  db-data:
